language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "tip"

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - go get -v -t .

script:
  - scripts/check-fmt.sh
  - go get -u golang.org/x/lint/golint
  - golint ./... | grep -v vendor/
  - make
  - scripts/check-code-generation-ran.sh
  - scripts/acceptance-tests.sh

matrix:
    allow_failures:
        - go: tip
